Webworks\AdminBundle\Entity\SystemModule:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        active:
            type: boolean
            nullable: true
        required:
            type: boolean
        menuItemText:
            type: string
            length: 255
            column: menu_item_text
        menuOrder:
            type: integer
            column: menu_order
            nullable: true
        developerName:
            type: string
            length: 255
            column: developer_name
            nullable: true
        developerUrl:
            type: string
            length: 255
            column: developer_url
            nullable: true
        systemMainRoute:
            type: string
            length: 255
            column: system_main_route
    lifecycleCallbacks: {  }
