parameters:
#    webworks_fixtures.example.class: Webworks\FixturesBundle\Example

services:
#    webworks_fixtures.example:
#        class: %webworks_fixtures.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
