parameters:
#    webworks_admin.example.class: Webworks\AdminBundle\Example

services:
#    webworks_admin.example:
#        class: %webworks_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
