parameters:
#    webworks_client.example.class: Webworks\ClientBundle\Example

services:
#    webworks_client.example:
#        class: %webworks_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
